feat: develop pin-input
Tap30/web-components pull request #91
Opened 2024-05-08 10:07 UTC by hossein-nas

This is a draft version of developing process of `Pin Input` component.

closes #40

2024-05-14 09:59 UTC, majidsajadi commented on src/pin-input-cell/pin-input-cell.ts
> +  @property({ reflect: true, type: Boolean, attribute: 'has-error' }) hasError =
we are using `error` for this attribute in other components. ex. `text-field`

2024-05-14 09:59 UTC, majidsajadi commented on src/pin-input-cell/pin-input-cell.ts
> +  }
remove please

2024-05-14 09:59 UTC, majidsajadi commented on src/pin-input-cell/pin-input-cell.ts
> +      this._cell.focus?.();
I guess optional chaining is unnecessary here

2024-05-14 09:59 UTC, majidsajadi commented on src/pin-input-cell/pin-input-cell.ts
> +      [8, 9, 13, 27, 46, 110, 190].includes(event.keyCode) ||
`event.keyCode` is deprecated. use `event.key` instead.

2024-05-14 09:59 UTC, majidsajadi commented on src/pin-input/pin-input.ts
`pin-input` should be a form control element using `elementInternal`. so we can use the browser native auto-fill

2024-05-14 09:59 UTC, majidsajadi commented on src/pin-input-cell/pin-input-cell.ts
To enhance simplicity and readability, consider moving most of the logic to the pin-input component. For instance, handling keyboard events could be consolidated within the pin-input element, rather than having both components engaged in event handling

2024-05-14 10:00 UTC, majidsajadi commented on src/pin-input/index.ts
> +}
export the `types` too.

2024-09-26 19:21 UTC, amir78729 commented
@hossein-nas Please resolve the conflicts of this PR.

2024-10-14 14:09 UTC, hossein-nas commented
@amir78729 @mimshins I resolved conflicts.

2024-10-14 17:56 UTC, amir78729 commented
@hossein-nas  LGTM, thanks

2024-10-20 09:13 UTC, mimshins requested changes

2024-12-04 16:01 UTC, closed without merging